project_id = "tukuyszayzkyckrfxqvt"

[functions.create-topup-bill]
verify_jwt = false

[functions.raudhahpay-webhook]
verify_jwt = false

[functions.process-transfer]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.daily-sales-email]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.manage-pin]
verify_jwt = false

[functions.api-register-app]
verify_jwt = false

[functions.api-authorize]
verify_jwt = false

[functions.api-revoke]
verify_jwt = false

[functions.api-balance]
verify_jwt = false

[functions.api-charge]
verify_jwt = false

[functions.api-charge-status]
verify_jwt = false
